### ISSUE TITLE
swagger-jsdoc-generator is not generating into the file

### ISSUE THREAD

**Issue by saad-ai-dev** [lmammino/swagger-jsdoc-generator#8]
Hi folks,
Hope you are all doing well.
I am new to swagger-jsdoc-generator I want the generator to generate it to the file rather than printing all on the command line 

I have used this command as mentioned in the doc but still not working.

`swagger-jsdoc-generator config.js | mySwaggerDoc.json`

Thanks in advance

**Comment by lmammino** [comment]
Have you tried the following?

```bash
swagger-jsdoc-generator config.js > mySwaggerDoc.json
```

Hopefully this helps

**Comment by saad-ai-dev** [comment]
> Have you tried the following?
> 
> ```shell
> swagger-jsdoc-generator config.js > mySwaggerDoc.json
> ```
> 
> Hopefully this helps

Thank you it works
